### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by neicore** [NuruProgramming/nyaraka#5]
https://nyaraka.vercel.app/en/function

**Comment by mwanyumba7** [comment]
Hello @neicore I am requesting to work on this issue

**Comment by neicore** [comment]
Hello @mwanyumba7 I have assigned you the issue. looking forward to your pr

**Comment by neicore** [comment]
Hello @mwanyumba7, I have completed other pending issues so I will reassign this to me so I can complete it today as well.
