### ISSUE TITLE
Search Functionality 

### ISSUE THREAD

**Issue by fredygerman** [NuruProgramming/nyaraka#52]
Having a simple functioning Search bar will be cool.

**Comment by neicore** [comment]
Sounds good. Vitepress supports Algolia search so I or someone can add it.

**Comment by alphaolomi** [comment]
I propose we start using Local Search with i18n while we apply for Algolia DocSearch
I will submit another PR for Algolia when we have the credentials.

Why start with Local? See [priority on who can apply](https://docsearch.algolia.com/docs/who-can-apply#priority)

Other Resources related:
- https://vitepress.dev/reference/default-theme-search
- https://docsearch.algolia.com/docs/what-is-docsearch/
- https://docsearch.algolia.com/apply/
